package com.hospital.backend.service;

import com.hospital.backend.model.Patient;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.draw.LineSeparator;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;

@Service
@RequiredArgsConstructor
public class PdfExportService {

    public byte[] generatePatientPdf(Patient patient) throws DocumentException {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        PdfWriter.getInstance(document, out);
        document.open();

        Font titleFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, new BaseColor(30, 111, 204));
        Paragraph title = new Paragraph("MedNex Enterprise", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        Font subFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.GRAY);
        Paragraph sub = new Paragraph("Patient Medical History Report", subFont);
        sub.setAlignment(Element.ALIGN_CENTER);
        document.add(sub);

        document.add(Chunk.NEWLINE);
        document.add(new LineSeparator());
        document.add(Chunk.NEWLINE);

        Font headerFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
        Font normalFont = new Font(Font.FontFamily.HELVETICA, 11);

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);

        addTableRow(table, "Patient ID", String.valueOf(patient.getId()), headerFont, normalFont);
        addTableRow(table, "First Name", patient.getFirstName(), headerFont, normalFont);
        addTableRow(table, "Last Name", patient.getLastName(), headerFont, normalFont);
        addTableRow(table, "Age", patient.getAge() != null ? patient.getAge().toString() : "N/A", headerFont, normalFont);
        addTableRow(table, "Gender", patient.getGender(), headerFont, normalFont);
        addTableRow(table, "Phone", patient.getPhone(), headerFont, normalFont);
        addTableRow(table, "Email", patient.getEmail(), headerFont, normalFont);
        addTableRow(table, "Address", patient.getAddress() != null ? patient.getAddress() : "N/A", headerFont, normalFont);
        addTableRow(table, "Blood Group", patient.getBloodGroup() != null ? patient.getBloodGroup() : "N/A", headerFont, normalFont);
        addTableRow(table, "Date of Birth", patient.getDateOfBirth() != null ? patient.getDateOfBirth() : "N/A", headerFont, normalFont);
        addTableRow(table, "Tenant", patient.getTenantId(), headerFont, normalFont);

        document.add(table);
        document.add(Chunk.NEWLINE);

        if (patient.getMedicalHistory() != null && !patient.getMedicalHistory().isEmpty()) {
            Font sectionFont = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, new BaseColor(30, 111, 204));
            document.add(new Paragraph("Medical History", sectionFont));
            document.add(Chunk.NEWLINE);
            document.add(new Paragraph(patient.getMedicalHistory(), normalFont));
        }

        document.add(Chunk.NEWLINE);
        Font footerFont = new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY);
        Paragraph footer = new Paragraph("Generated by MedNex Enterprise | HIPAA Compliant", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addTableRow(PdfPTable table, String key, String value, Font keyFont, Font valueFont) {
        PdfPCell keyCell = new PdfPCell(new Phrase(key, keyFont));
        keyCell.setBackgroundColor(new BaseColor(240, 244, 255));
        keyCell.setPadding(8);
        keyCell.setBorderColor(new BaseColor(220, 220, 220));

        PdfPCell valueCell = new PdfPCell(new Phrase(value != null ? value : "N/A", valueFont));
        valueCell.setPadding(8);
        valueCell.setBorderColor(new BaseColor(220, 220, 220));

        table.addCell(keyCell);
        table.addCell(valueCell);
    }
}